<a href="https://colab.research.google.com/github/iam-shankar/DSML-FB07-ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

# Creating NumPy Arrays

In [ ]:
import numpy as np

In [ ]:
# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print(type(arr1))

1D Array: [1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr1

array([1, 2, 3, 4, 5])

# 2 dimensional array

In [ ]:
#2d list
list_2d=[[1,2,3],[4,5,6]]
len(list_2d)

2

In [ ]:
list_2d[0]

[1, 2, 3]

In [ ]:
list_2d[0][2]

3

In [ ]:
# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
a=[1,2,3,4]
b=[5,6,7,8]
arr3=np.array([a,b])
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


#NumPy Initialization

In [ ]:
# Array of Zeros
zeros = np.zeros((3, 4))  # 3 rows, 4 columns
print("Array of Zeros:\n", zeros)

Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Array of Ones
ones = np.ones((2, 3))  # 2 rows, 3 columns
print("Array of Ones:\n", ones)

Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Array with Range
arr_range = np.arange(1, 10, 2)  # Start at 1, end before 10, step 2
print("Array with Range:", arr_range)

Array with Range: [1 3 5 7 9]


In [ ]:
# Random Array
random_arr = np.random.rand(3, 3)  # 3x3 array with random values
print("Random Array:\n", random_arr)


Random Array:
 [[0.43084432 0.76692406 0.41872284]
 [0.48133982 0.46090671 0.29668658]
 [0.19886917 0.2956542  0.41729697]]


#Arrange Z numbers between X and Y

#Linspace

In [ ]:
np.linspace(0,20,5) # np.linspace(start,stop,num_of_samples)


array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

#inspecting the array : checking the shape of the array

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a.shape
#(2,3) (rows,cols)

(2, 3)

In [ ]:
len(a) #no. of rows

2

In [ ]:
type(a.shape)

tuple

In [ ]:
a.shape[0]  #no.rows

2

In [ ]:
a.shape[1] #no.cols

3

#reshape the array

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape=(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
ar=np.arange(24)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
ar.shape
#(20,)singlton tuple

(24,)

In [ ]:
b=ar.reshape(4,6) # reshape(no of rows, no of cols)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#reshaping to 3D array

In [ ]:
c=ar.reshape(2,3,4) #(no.arrays,rows,cols)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
c.shape

(2, 3, 4)

In [ ]:
d=ar.reshape(3,2,4) #(no.arrays,rows,cols)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

#checking dimension

In [ ]:
a.ndim

2

In [ ]:
b.ndim

2

In [ ]:
c.ndim

3

In [ ]:
d.ndim

3

#converting back to 1d array

In [ ]:
d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
d.shape

(3, 2, 4)

In [ ]:
c.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#find the number of elements in the array

In [ ]:
a.size

6

In [ ]:
c.size

24

#checking type of the data

In [ ]:
#checking type of the data
d.dtype

dtype('int64')

In [ ]:
#default type int
f=np.arange(24)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#changing the data type while creating the array
e=np.arange(24,dtype=float)
e

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

#2. Array Operations

In [ ]:
a1=[1,2]
a2=[3,4]

a1+a2 #concatenates list

[1, 2, 3, 4]

In [ ]:
a1=np.array([1,2])
a2=np.array([1,2])
a1+a2 #adds the value of the two arrays

array([2, 4])

In [ ]:
a1+10 #adds the number to all the values in the array

array([11, 12])

In [ ]:
a2+2

array([3, 4])

In [ ]:
a1*5

array([ 5, 10])

In [ ]:
arr = np.array([1, 2, 3, 4])

# Addition
print("Addition:", arr + 2)  # Adds 2 to each element

# Subtraction
print("Subtraction:", arr - 1)

# Multiplication
print("Multiplication:", arr * 3)

# Division
print("Division:", arr / 2)

# Power
print("Exponentiation:", arr ** 2)


Addition: [3 4 5 6]
Subtraction: [0 1 2 3]
Multiplication: [ 3  6  9 12]
Division: [0.5 1.  1.5 2. ]
Exponentiation: [ 1  4  9 16]


#Aggregate Functions


In [ ]:
arr = np.array([10, 20, 30, 40])

print("Sum:", np.sum(arr))  # Sum of all elements
print("Mean:", np.mean(arr))  # Average
print("Max:", np.max(arr))  # Maximum value
print("Min:", np.min(arr))  # Minimum value
print("Standard Deviation:", np.std(arr))  # Standard deviation


Sum: 100
Mean: 25.0
Max: 40
Min: 10
Standard Deviation: 11.180339887498949


#Element-wise Comparisons



In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 3, 2, 1])

# Element-wise comparison
print("Greater than:", arr1 > arr2)
print("Equality:", arr1 == arr2)


Greater than: [False False  True  True]
Equality: [False False False False]


#3. Array Indexing and Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("First Element:", arr[0])  # Access first element
print("Last Element:", arr[-1])  # Access last element


First Element: 10
Last Element: 50


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("First three elements:", arr[:3])  # Elements from index 0 to 2
print("Last two elements:", arr[-2:])  # Last two elements
print("Elements at even indices:", arr[::2])  # Step of 2

First three elements: [10 20 30]
Last two elements: [40 50]
Elements at even indices: [10 30 50]


#Slicing in 2D Arrays

2D Slicing Syntax:

array[row_slicing, column_slicing]

array[start_row:end_row, start_col,end_col]



In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("First row:", arr2[0])  # Access first row
print("First column:", arr2[:, 0])  # Access first column
print("Sub-matrix:\n", arr2[1:, 1:])  # Bottom-right sub-matrix


First row: [1 2 3]
First column: [1 4 7]
Sub-matrix:
 [[5 6]
 [8 9]]


In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## row indexing

In [ ]:
arr2[0] #first row row indexing

array([1, 2, 3])

In [ ]:
arr2[-1] #accessing last row

array([7, 8, 9])

In [ ]:
arr2[1] #accessing specific row

array([4, 5, 6])

In [ ]:
arr2[0:2] #accessing rows 0 and 1 , 2 is exclusive

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[1]

array([4, 5, 6])

## column indexing

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[:,0] #first give row ":"" means all rows and 0 indicates 1st column

array([1, 4, 7])

In [ ]:
arr2[:,1:3] #display 2 and 3 column

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
arr2[:,1:] #similar to above

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
arr2[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[:2,-2:]  #similar to above

array([[2, 3],
       [5, 6]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr2[1:,:2]

array([[4, 5],
       [7, 8]])

In [ ]:
arr2[1:,:1]

array([[4],
       [7]])

In [ ]:
arr2[1:,0]

array([4, 7])

# End of NumPy Notes

#Weekly Calories Data

In [ ]:
import numpy as np

# Daily calorie intake for one week (Monday to Sunday)
calories = np.array([1800, 2000, 2200, 2500, 2300, 1900, 2100])

# First three days of the week (Monday to Wednesday)
first_three_days = calories[:3]
print("Calories for the first three days (Monday-Wednesday):", first_three_days)

# Weekend calories (Saturday and Sunday)
weekend = calories[-2:]
print("Calories for the weekend (Saturday-Sunday):", weekend)

# Middle three days of the week (Wednesday, Thursday, Friday)
middle_three_days = calories[2:5]
print("Calories for the middle three days (Wednesday-Friday):", middle_three_days)


Calories for the first three days (Monday-Wednesday): [1800 2000 2200]
Calories for the weekend (Saturday-Sunday): [1900 2100]
Calories for the middle three days (Wednesday-Friday): [2200 2500 2300]


#Weekly Step Count

Let's use a 2D array to demonstrate slicing for step counts over two weeks.



In [ ]:
# Step count data for two weeks (rows = weeks, columns = days)
steps = np.array([
    [8000, 7500, 8200, 10000, 9000, 7000, 8500],  # Week 1
    [8100, 7600, 8300, 10100, 9100, 7200, 8600]   # Week 2
])

# Steps for the first three days of both weeks
first_three_days = steps[:, :3]
print("Steps for the first three days of both weeks:\n", first_three_days)

# Steps for the weekend of both weeks (Saturday and Sunday)
weekend = steps[:, -2:]
print("Steps for the weekend of both weeks:\n", weekend)
'''In this case, [:, -2:] means:

: → Select all rows.

-2: → Select the last two columns (Saturday and Sunday).'''
# Steps for the middle three days of each week
middle_three_days = steps[:, 2:5]
print("Steps for the middle three days of each week:\n", middle_three_days)


Steps for the first three days of both weeks:
 [[8000 7500 8200]
 [8100 7600 8300]]
Steps for the weekend of both weeks:
 [[7000 8500]
 [7200 8600]]
Steps for the middle three days of each week:
 [[ 8200 10000  9000]
 [ 8300 10100  9100]]


#4. NumPy Functions

#Mathematical Functions


In [ ]:
arr = np.array([0, np.pi/2, np.pi])

print("Sin:", np.sin(arr))  # Sine values
print("Cos:", np.cos(arr))  # Cosine values
print("Exponential:", np.exp(arr))  # Exponential
print("Logarithm:", np.log(np.array([1, np.e, np.e**2])))  # Natural log


Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponential: [ 1.          4.81047738 23.14069263]
Logarithm: [0. 1. 2.]


#Reshaping and Transposing


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape((2, 3))  # Convert to 2x3 array
print("Reshaped Array:\n", reshaped)

transposed = reshaped.T  # Transpose the array
print("Transposed Array:\n", transposed)


Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


#Sorting


In [ ]:
arr = np.array([4, 1, 3, 9, 2])

sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)


Sorted Array: [1 2 3 4 9]


#5. Broadcasting
Broadcasting allows NumPy to perform operations on arrays of different shapes, aligning smaller arrays with larger ones.

In [ ]:
arr = np.array([1, 2, 3])
matrix = np.array([[10], [20], [30]])

# Broadcasting addition
result = arr + matrix
print("Broadcasted Result:\n", result)


Broadcasted Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


#Problem: Analyzing Sales Data


In [ ]:
# Sales data for three products over four weeks
sales = np.array([[200, 220, 250],  # Week 1
                  [210, 240, 260],  # Week 2
                  [220, 230, 270],  # Week 3
                  [230, 250, 280]]) # Week 4

# Total sales for each week
total_sales_per_week = np.sum(sales, axis=1)
print("Total Sales per Week:", total_sales_per_week)

# Total sales for each product
total_sales_per_product = np.sum(sales, axis=0)
print("Total Sales per Product:", total_sales_per_product)

# Average sales per product
average_sales_per_product = np.mean(sales, axis=0)
print("Average Sales per Product:", average_sales_per_product)


Total Sales per Week: [670 710 720 760]
Total Sales per Product: [ 860  940 1060]
Average Sales per Product: [215. 235. 265.]


In [ ]:
import numpy as np

# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the array a
print ("Original array:\n ", a)

# Convert nd array to 1D array
c = a.flatten()

# Flatten passes copy of
# original array to 'c'
print ("\nFlatten array using flatten: ", c)
print ("Original array:\n ", a)

Original array:
  [[1 2 3 4]
 [3 1 4 2]]

Flatten array using flatten:  [1 2 3 4 3 1 4 2]
Original array:
  [[1 2 3 4]
 [3 1 4 2]]


In [ ]:
c[2] = 33

print ("Flatten array: ", c)

# Let's print the array a
print ("\nOriginal array:\n ", a)


Flatten array:  [ 1  2 33  4  3  1  4  2]

Original array:
  [[1 2 3 4]
 [3 1 4 2]]


In [ ]:
import numpy as np

# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the array a
print ("Original array:\n ", a)

ra = np.ravel(a)
print ("\nFlatten array using ravel: ", ra)


Original array:
  [[1 2 3 4]
 [3 1 4 2]]

Flatten array using ravel:  [1 2 3 4 3 1 4 2]


In [ ]:
ra[3] = 44

print ("Flatten array: ", ra)

# Let's print the array a
print ("\nOriginal array:\n ", a)


Flatten array:  [ 1  2  3 44  3  1  4  2]

Original array:
  [[ 1  2  3 44]
 [ 3  1  4  2]]


In [ ]:
import numpy as np

In [ ]:

arr3d=np.random.randint(1,50,(4,4))
arr3d

array([[39, 29, 10, 30],
       [ 1, 32, 19, 17],
       [33, 47, 27, 20],
       [12,  2, 18, 39]])

In [ ]:
arr3d[:-1]

array([[39, 29, 10, 30],
       [ 1, 32, 19, 17],
       [33, 47, 27, 20]])

In [ ]:
arr3d[:-1,:-1]

array([[39, 29, 10],
       [ 1, 32, 19],
       [33, 47, 27]])

In [ ]:

arr3d=np.random.randint(1,50,(3,2,2))
arr3d

array([[[10, 37],
        [35, 23]],

       [[31, 41],
        [ 9, 32]],

       [[49, 37],
        [42, 41]]])

In [ ]:
arr3d[:1,:,:]

array([[[10, 37],
        [35, 23]]])

In [ ]:
arr3d[0]

array([[10, 37],
       [35, 23]])

In [ ]:
arr3d[:,:1,:1]

array([[[10]],

       [[31]],

       [[49]]])

In [ ]:
arr3d[:,1:,:1]

array([[[35]],

       [[ 9]],

       [[42]]])

In [ ]:
a=np.random.randint(1,10,(2,2))
b=np.random.randint(1,10,(2,2))
a

array([[3, 8],
       [9, 9]])

In [ ]:
b

array([[4, 3],
       [4, 4]])

In [ ]:
np.dstack((a,b))

array([[[3, 4],
        [8, 3]],

       [[9, 4],
        [9, 4]]])